spring.application.name=TelegramBot_Application_Demo


#==================================Server===============================================
server.port=8090

#==================================Database===============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/TelegramBot_Demo
spring.datasource.username=postgres
spring.datasource.password=${SPRING_PASSWORD}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#========================================== Migration ==========================================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=false
spring.flyway.clean-on-validation-error=true
spring.flyway.validate-on-migrate=false
spring.flyway.schemas=public
spring.flyway.baseline-on-migrate=true

#========================================== Swagger Open API ==========================================
springdoc.swagger-ui.path=/telegrambot
springdoc.swagger-ui.show-extensions=true

#==================================Telegram Bot===============================================
bot.name=my_smart_java_2026_bot
bot.token=${SPING_TELEGRAM_TOKEN:8946937012:AAHCLuAQGXtkP1zfhUV8p0AiX_NsNhpUflQ}